Scheduling based on mix frames
openqasm/qe-compiler pull request #300
Opened 2024-03-18 22:57 UTC by reza-j

This PR introduces scheduling of a quantum circuit based on mix frames in order to reduce the overall duration of the scheduled pulse sequence.

2024-03-26 19:14 UTC, taalexander requested changes
A few small questions

2024-03-26 19:14 UTC, taalexander commented on lib/Dialect/Pulse/Transforms/Scheduling.cpp
> +          getMixFramesBlockIds(quantumGateCallSequenceOp);
What is a mix frame block id?

2024-03-26 19:14 UTC, taalexander commented on lib/Dialect/Pulse/Transforms/Scheduling.cpp
> +      if (mixFrameToNextAvailabilityMap[id] < nextAvailableTimeOfAllMixFrames)
It seems like this condition can be combined into a single boolean and `if`? (can use an intermediary value)

2024-03-27 19:08 UTC, kitbarton approved these changes
LGTM!

Please update the copyright dates in the files changed to include 2024 (for some reason GitHub won't allow me to add a comment to lines that are not changed).

2024-03-28 15:25 UTC, taalexander approved these changes
LGTM

2024-03-28 15:30 UTC, merged